name = "garfield"
version = "0.1.0"
defaultTargets = ["garfield"]

[[lean_lib]]
name = "Garfield"

[[lean_exe]]
name = "garfield"
root = "Main"

[[require]]
name = "Algolean"
scope = "Shreyas4991"
rev = "v4.30.0"

[[require]]
name = "Cslib"
scope = "leanprover"
rev = "v4.30.0"

[[require]]
name = "Mathlib"
scope = "leanprover-community"
rev = "v4.30.0"
